const TAGS = [
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category12"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category13"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {category: "category11"},
    {scale: 0.6, name: "customShape0"},
    {scale: 0.6, name: "customShape1"},
    {scale: 0.6, name: "customShape2"},
    {scale: 0.6, name: "customShape3"},
    {scale: 0.6, name: "customShape4"},
    {scale: 0.6, name: "customShape5"},
    {scale: 0.6, name: "customShape0"},
    {scale: 0.6, name: "customShape1"},
    {scale: 0.6, name: "customShape2"},
    {scale: 0.6, name: "customShape3"},
    {scale: 0.6, name: "customShape4"},
    {scale: 0.6, name: "customShape5"},
    {scale: 0.6, name: "customShape0"},
    {scale: 0.6, name: "customShape1"},
    {scale: 0.6, name: "customShape2"},
    {scale: 0.6, name: "customShape3"},
    {scale: 0.6, name: "customShape4"},
    {scale: 0.6, name: "customShape5"},
    {scale: 0.6, name: "customShape0"},
    {scale: 0.6, name: "customShape1"},
    {scale: 0.6, name: "customShape2"},
    {scale: 0.6, name: "customShape3"},
    {scale: 0.6, name: "customShape4"},
    {scale: 0.6, name: "customShape5"},
].sort(() => Math.random() - 0.5);

export default TAGS;